name: Docker Build and Run
on: [push]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t matthieufmt/img-ci:${{ github.sha }} .
          docker login -u matthieufmt -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push matthieufmt/img-ci:${{ github.sha }}

      - name: Run Docker container
        run: docker run -d -p 8080:8080 matthieufmt/img-ci:${{ github.sha }}
