name: Vérifier le code, installer les dépendances et exécuter les tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Installer les dépendances
        run: npm install

      - name: Vérifier le code
        run: npm run lint

      - name: Exécuter les tests
        run: npm test
