name: Dependabot
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Dependabot
        uses: dependabot/dependabot-core@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: "/"
          update: "true"
          schedule: "interval: 5m"
